### ISSUE TITLE
Adding this plugin to the plugin list breaks other Babel functionality

### ISSUE THREAD

**Issue by RobbieGM** [leonardfactory/babel-plugin-transform-typescript-metadata#21]
Hi @leonardfactory, 
I noticed that when I add this plugin to my plugin list it breaks the other transformations in the config. I get this error message when it's in there:
```
C:\Users\Robbie\Code\ginger\src\backend\resolvers\RecipeResolver.ts:1       
(function (exports, require, module, __filename, __dirname) { import {      
                                                                     ^      

SyntaxError: Unexpected token {
```
This is the same error message I get if I do not use Babel at all (or remove the `react-app` preset). If I don't use the plugin, metadata reflection doesn't work (and TypeORM gives me errors) but everything else does. My package.json babel config is this:
```
"babel": {
    "plugins": [
      "babel-plugin-transform-typescript-metadata",
      "@babel/plugin-proposal-optional-chaining",
      "@babel/plugin-proposal-nullish-coalescing-operator"
    ],
    "presets": [
      "react-app"
    ]
  }
```
If you need more information, my project repository is here: https://github.com/RobbieGM/ginger
Thanks for your help!

**Comment by wtho** [comment]
Hey, I think you need at least the preset `@babel/preset-typescript` for this to work, probably even `@babel/plugin-proposal-decorators` and `@babel/plugin-proposal-class-properties`.

See the [usage section](https://github.com/leonardfactory/babel-plugin-transform-typescript-metadata#usage) for more.

Don't forget to close this issue, if this helped you. Cheers!

**Comment by RobbieGM** [comment]
`babel-preset-react-app` already contains those three plugins (at least for TS environments, and after changing `presets` to `[["react-app", {"typescript": true}]]` I verified that this is true), so it should be working, right? Also, if it makes a difference, `babel-preset-react-app` uses the legacy version of decorators.

**Comment by wtho** [comment]
Ok I guess then we need more information. A minimal code example of the class where the error occurs would be great.

**Comment by RobbieGM** [comment]
Oh, I figured something out. Doesn't quite solve the issue, but what's going on is that this seems to happen when I tell TypeORM to load entities by file name and (I assume) parse the TypeScript itself, which may complicate things. A simple code example:
**jest-setup.ts**
```ts
import {createConnection} from "typeorm";

export default function startApiTestServer() {
  await createConnection({
    type: 'postgres',
    url,
    entities: [`${__dirname}/data-types/**/*.ts`],
    synchronize: true // Will force-update schema in production
  });
}
```

**data-types/Recipe.ts**

```ts
import {justAboutAnything} from "anywhere";
// ^^ error occurs here
```

**Comment by wtho** [comment]
Ok, I do not know about TypeORM, but I guess you should clarify how it reads the types from your sources.

**Comment by leonardfactory** [comment]
Mh, I use typeorm but usually you can't work with `.ts` files. You need compiled JS files or directly imported entities (i.e. `import { User } from 'User.entity'` and then `entities: [User,...]`).
I'm pretty sure you can't use `createConnection` with typescript sources (I tried and it was a mess)

**Comment by RobbieGM** [comment]
It works just fine the way it's configured when run with `ts-node` but breaks when babel is involved. I'll give it a try with direct entity class assignment as described. Also, @wtho TypeORM uses decorators and `reflect-metadata` magic to read types from sources. An example of a class written for TypeORM:
```ts
@Entity()
export class User {

    @PrimaryGeneratedColumn()
    id: number;

    @Column()
    firstName: string;

    @Column()
    lastName: string;

    @Column()
    age: number;

}
```
