### ISSUE TITLE
Add info about resolving bundler warnings to README

### ISSUE THREAD

**Issue by gshokanov** [leonardfactory/babel-plugin-transform-typescript-metadata#46]
Hey!
When using this plugin I found that webpack complains about missing exports due to types not being removed by babel when used in inversify decorators. Although everything works fine these warnings can be resolved by using type imports:
```ts
import { injectable, inject } from 'inversify';
import type { Service } from './Service';
import { ServiceIdentifier } from './ServiceIdentifier';

@injectable
export class OtherService {
  constructor(
    @inject(ServiceIdentifier) service: Service
  ) {}
}
```
Just a small suggestion to add this to README if you think it fits there as some people might want to get rid of the warnings but don't know how.

**Comment by gshokanov** [comment]
BTW I don't have any experience writing Babel plugins but maybe it's possible to automatically rewrite imports this way through the plugin?

**Comment by linayanse** [comment]
> Hey!
> When using this plugin I found that webpack complains about missing exports due to types not being removed by babel when used in inversify decorators. Although everything works fine these warnings can be resolved by using type imports:
> 
> ```ts
> import { injectable, inject } from 'inversify';
> import type { Service } from './Service';
> import { ServiceIdentifier } from './ServiceIdentifier';
> 
> @injectable
> export class OtherService {
>   constructor(
>     @inject(ServiceIdentifier) service: Service
>   ) {}
> }
> ```
> 
> Just a small suggestion to add this to README if you think it fits there as some people might want to get rid of the warnings but don't know how.

thx you for this solution.

**Comment by leonardfactory** [comment]
I'll add it to README in the pitfalls section. Thank you 😄
