### ISSUE TITLE
Add a babel preset with this enabled

### ISSUE THREAD

**Issue by fivethreeo** [leonardfactory/babel-plugin-transform-typescript-metadata#47]
I did the work but great if someone took it off my hands

https://github.com/jaredpalmer/razzle/tree/custom-typescript-preset/packages/babel-preset-typescript

**Comment by leonardfactory** [comment]
Hi @fivethreeo thank you! I'm sure this would be cool, but doesn't match the repository scope. I'll leave this open in case someone else find it useful / would like to publish it

**Comment by fivethreeo** [comment]
By the way I use this plugin without the preset here: https://github.com/jaredpalmer/razzle/tree/master/examples/with-typeorm-graphql 😀
