### ISSUE TITLE
design:paramtypes does not work with object assignment

### ISSUE THREAD

**Issue by jeffborg** [leonardfactory/babel-plugin-transform-typescript-metadata#48]
Been using type-graphql and came across this issue

Here is a sample class which returns a void type for the argument

```ts
class Demo {
  @Method()
  test(@Args(): { destructedProp } : ClassType) {}
}
```

This sample works
```ts
class Demo {
  @Method()
  test(@Args(): arg : ClassType) {}
}
```

It seems the `param.type` here https://github.com/leonardfactory/babel-plugin-transform-typescript-metadata/blob/master/src/metadata/serializeType.ts#L25 is `ObjectPattern` and this results in returning voidZero()

**Comment by leonardfactory** [comment]
Thank you @jeffborg ! Released it in v0.3.2 👍🏼
